name: faceoff

logger:
  level: "INFO"

session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 2592000

socket:
  address: "0.0.0.0"
  port: 7350
  max_message_size_bytes: 8192

console:
  port: 7351

runtime:
  path: "/nakama/data/modules"

metrics:
  prometheus_port: 9100
