#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_path="${FACE_OFF_PRODUCTION_ENV_FILE:-${project_root}/.env.production}"
domain="${NAKAMA_DOMAIN:-}"
email="${ACME_EMAIL:-}"
force=0

usage() {
    cat <<'EOF'
Usage: tools/generate_production_secrets.sh --domain play.example.com --email ops@example.com [--force]

Creates a chmod 600 .env.production file with fresh random Nakama and PostgreSQL secrets.
Existing files are preserved unless --force is supplied.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)
            [[ $# -ge 2 ]] || { echo "--domain requires a value" >&2; exit 2; }
            domain="$2"
            shift 2
            ;;
        --email)
            [[ $# -ge 2 ]] || { echo "--email requires a value" >&2; exit 2; }
            email="$2"
            shift 2
            ;;
        --force)
            force=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z "$domain" || "$domain" == "play.example.com" || "$domain" == *"://"* || "$domain" == */* || "$domain" == *" "* ]]; then
    echo "Pass a real DNS hostname with --domain, for example play.example.com." >&2
    exit 1
fi
if [[ -z "$email" || "$email" == "ops@example.com" || "$email" != *@*.* ]]; then
    echo "Pass a real ACME notification address with --email." >&2
    exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required to generate production secrets." >&2
    exit 1
fi
if [[ -e "$output_path" && "$force" -ne 1 ]]; then
    echo "$output_path already exists. Use --force only when intentionally rotating every production secret." >&2
    exit 1
fi

secret() {
    openssl rand -hex 32
}

mkdir -p "$(dirname "$output_path")"
umask 077
cat > "$output_path" <<EOF
# Generated by tools/generate_production_secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of version control and back it up in a password manager.
NAKAMA_DOMAIN=$domain
ACME_EMAIL=$email

POSTGRES_DB=nakama
POSTGRES_USER=nakama
POSTGRES_PASSWORD=$(secret)

NAKAMA_NODE_NAME=faceoff
NAKAMA_SERVER_KEY=$(secret)
NAKAMA_SESSION_ENCRYPTION_KEY=$(secret)
NAKAMA_REFRESH_ENCRYPTION_KEY=$(secret)
NAKAMA_RUNTIME_HTTP_KEY=$(secret)
NAKAMA_CONSOLE_SIGNING_KEY=$(secret)
NAKAMA_CONSOLE_USERNAME=faceoff-admin
NAKAMA_CONSOLE_PASSWORD=$(secret)

BACKUP_DIR=/var/backups/faceoff
BACKUP_RETENTION_DAYS=14
PROMETHEUS_RETENTION=15d
PROMETHEUS_PORT=9090
EOF
chmod 600 "$output_path"

echo "Generated production environment: $output_path"
echo "The private values are not printed. Store a recovery copy before deploying."
